name: pasqal-quantum-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pytorch
  - pip
  - pip:
      - qadence
      - pulser
      - quantum-evolution-kernel